### ISSUE TITLE
Many to many with relationship url

### ISSUE THREAD

**Issue by firstgeneration** [redux-json-api/redux-json-api#135]
Is there support for a many to many as shown here?:
http://jsonapi.org/format/#crud-updating-to-many-relationships

Would be awesome to `POST/PATCH/DELETE` to
`/primary_resource/:id/relationships/related_resource`

**Comment by Nopzen** [comment]
Hi @firstgeneration 

As of now no, we dont support this.

If someone would be up for creating a PR for this i think it would be nice to ship with the v2.

**Comment by egeriis** [comment]
For now it's not supported through `relationships/relation` endpoint. But you are able to PATCH a resource with the updated `relationships` property :)

**Comment by etiennecaldo** [comment]
Hi guys, 

First of all thank you for your work on this library.

I wanted to know if this feature is planned in a near future? On my side I have a backend library that doesn't allow PATCH of relationships' resource via resource api. I must use relationship API. I'll try to have a look and share a PR but I am a redux newbie.

By the way, while looking at the code I saw something strange in state-mutation.js

For **API_UPDATE_FAILED** and **API_DELETE_FAILED**, setIsInvalidatingForExistingResource is called with following arguments: 

`setIsInvalidatingForExistingResource(state, { type, id }, IS_DELETING) setIsInvalidatingForExistingResource(newState, { type, id }, IS_UPDATING)`

should we have instead 

`setIsInvalidatingForExistingResource(state, { type, id }) setIsInvalidatingForExistingResource(newState, { type, id })`

in order to clear the Invalidating flag?

**Comment by egeriis** [comment]
Hey @etiennecaldo 

Are you looking to patch something like `/resource/:id/relationship` ?

At the time of writing this lib, that wasn't something that had been described by JSON API iirc.

That resource should also have a canonical URL though, which should correspond to `/relatedResource/:id`, so I don't know if this is really a JSON API issue if you _have_ to PATCH through relationship URL.

---

Looks like you're absolutely right about `setIsInvalidatingForExistingResource`. That should be fixed 😄

**Comment by dakota** [comment]
This is handled in #193
