### ISSUE TITLE
Links to state

### ISSUE THREAD

**Issue by DimaelVertigo** [redux-json-api/redux-json-api#166]
Hello.
How `API_READ` return only `tasks` and `include`. 
Can I include to state also `links: {}` and `meta: {}` from response?

**Comment by egeriis** [comment]
You mean the root `links` and `meta` properties? They're not automatically populated to redux state, no. The reason is that redux-json-api takes care of storing resources independent of requests, and `root.links`, `root.meta` are request-specific.

You can easily take care of storing them in whatever way you need, while keeping the benefit of having redux-json-api store your resources:

```js
const tasksResponse = await readEndpoint('/data/tasks');
const responseLinks = tasksResponse.links;
const responseMeta = tasksResponse.meta;
```

**Comment by DimaelVertigo** [comment]
Yes, I mean the root links and meta properties. 
![image](https://user-images.githubusercontent.com/8653710/45359578-a07ce000-b5d5-11e8-8399-099b71d7fb15.png)

I try to include `root.links` and `root.meta` to state and to props later.

```
componentDidMount() {
    this.props.dispatch(readEndpoint('/domains?include=remote_access'));
  }
```

**Comment by DimaelVertigo** [comment]
```
  componentDidMount() {
    this.props.dispatch(readEndpoint('/domains?include=remote_access'))
      .then(r => {
        console.log(r.body.links);
        console.log(r.body.meta)
      });
  }
```
I got access to `links` and `meta`. Thank you!
